language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - "8"
before_install:
  - npm i npm@^6 -g
install:
  - npm install
script:
  - npm run build
  - npm run test:ci
services:
  - xvfb
notifications:
  email: false