sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
before_install:
  - npm i npm@^6 -g
install:
  - npm install
script:
  - npm run build
  - npm run test:ci
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
notifications:
  email: false